#!/bin/bash -x
set -e

[ -d .requirements ]
cd .requirements
for reqfile in requirements*txt ; do
    TEMPDIR="$(mktemp -d /tmp/req.XXXXXXX)"
    virtualenv -ppython3 "$TEMPDIR"
    source "$TEMPDIR"/bin/activate
    pip install -r "$reqfile"
    pip freeze | sort -n > "../$reqfile"
    rm -rf "$TEMPDIR"
done
